"""SessionBridge — SOUL to Hermes Profile orchestration.

Translates AgentArk fleet agent identities into live Hermes profiles
so the user's terminal prompt reflects the active agent persona.

Flow:
  SOUL.md → agent_persona.md → ~/.hermes/profiles/agentark-<name>/
                                              ↓
                              export HERMES_PROFILE=agentark-<name>
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional


# ── Constants ──────────────────────────────────────────────────────────

HERMES_HOME = Path(os.environ.get("HERMES_HOME", Path.home() / ".hermes"))
AGENTARK_STATE = Path.home() / ".agentark"
STATE_FILE = AGENTARK_STATE / "active_session"

# Where AgentArk SOUL.md files live (project-level fleet profiles)
_FLEET_PROFILES_DIR = Path(__file__).resolve().parent.parent.parent / "fleet" / "profiles"


# ── Data structures ────────────────────────────────────────────────────


@dataclass
class SoulDoc:
    """Parsed SOUL.md fields."""
    title: str
    identity: str
    responsibilities: list[str]
    expertise: list[str]
    personality: str
    communication: str
    skills: list[str]
    raw: str = ""

    @property
    def role_name(self) -> str:
        """Short role name from title (e.g. 'DevOps Engineer')."""
        return self.title.lstrip("# ").strip()


@dataclass
class SessionStatus:
    """Current session state."""
    active: Optional[str] = None  # currently activated agent name, or None
    attached: list[str] = field(default_factory=list)
    available: list[str] = field(default_factory=list)


# ── SOUL.md Parser ─────────────────────────────────────────────────────


def _parse_soul(content: str) -> SoulDoc:
    """Parse a Chinese-format SOUL.md into structured fields."""
    lines = content.split("\n")
    title = lines[0] if lines else "# Unknown"

    # Section parsers — look for ## headers and collect until next ##
    sections: dict[str, list[str]] = {}
    current_section = None
    for line in lines[1:]:
        if line.startswith("## "):
            current_section = line[3:].strip()
            sections[current_section] = []
        elif current_section and line.startswith("---"):
            break  # stop at horizontal rule (footer metadata)
        elif current_section:
            sections[current_section].append(line)

    def section_text(name: str) -> str:
        return "\n".join(sections.get(name, [])).strip()

    def section_list(name: str) -> list[str]:
        items = []
        for line in sections.get(name, []):
            stripped = line.strip()
            if stripped.startswith("- "):
                items.append(stripped[2:])
            elif stripped and not stripped.startswith("#"):
                items.append(stripped)
        return items

    return SoulDoc(
        title=title,
        identity=section_text("身份"),
        responsibilities=section_list("核心职责"),
        expertise=section_list("专业领域"),
        personality=section_text("个性风格"),
        communication=section_text("沟通方式"),
        skills=section_list("技能列表"),
        raw=content,
    )


# ── SOUL → Persona conversion ──────────────────────────────────────────


def soul_to_persona(soul: SoulDoc) -> str:
    """Convert a parsed SOUL.md into a Hermes agent_persona.md body."""
    parts: list[str] = []

    # Role header
    parts.append(f"# {soul.role_name}")
    parts.append("")

    # Identity
    if soul.identity:
        parts.append(soul.identity)
        parts.append("")

    # Responsibilities
    if soul.responsibilities:
        parts.append("## Core Responsibilities")
        for r in soul.responsibilities:
            parts.append(f"- {r}")
        parts.append("")

    # Expertise
    if soul.expertise:
        parts.append("## Areas of Expertise")
        for e in soul.expertise:
            parts.append(f"- {e}")
        parts.append("")

    # Personality
    if soul.personality:
        parts.append("## Personality & Style")
        parts.append(soul.personality)
        parts.append("")

    # Communication
    if soul.communication:
        parts.append("## Communication Style")
        parts.append(soul.communication)
        parts.append("")

    # Skills hint
    if soul.skills:
        parts.append("## Preferred Skills")
        for s in soul.skills:
            parts.append(f"- {s}")
        parts.append("")

    # Footer
    parts.append("---")
    parts.append(f"_Generated by AgentArk SessionBridge from fleet profile_")

    return "\n".join(parts)


# ── Session Manager ────────────────────────────────────────────────────


class SessionManager:
    """Manage the AgentArk ↔ Hermes session bridge.

    All operations are idempotent — attach/detach/activate can be run
    multiple times safely.
    """

    def __init__(self):
        self.profiles_dir = HERMES_HOME / "profiles"
        AGENTARK_STATE.mkdir(parents=True, exist_ok=True)

    # ── Discovery ──────────────────────────────────────────────────

    def list_available(self) -> list[str]:
        """List agents that have SOUL.md files in fleet profiles."""
        agents = []
        if _FLEET_PROFILES_DIR.exists():
            for d in sorted(_FLEET_PROFILES_DIR.iterdir()):
                if d.is_dir() and (d / "SOUL.md").exists():
                    agents.append(d.name)
        return agents

    def list_attached(self) -> list[str]:
        """List agentark-* profiles already created in Hermes."""
        if not self.profiles_dir.exists():
            return []
        attached = []
        for d in sorted(self.profiles_dir.iterdir()):
            if d.is_dir() and d.name.startswith("agentark-"):
                # Check it has a persona
                if (d / "agent_persona.md").exists():
                    attached.append(d.name[len("agentark-"):])
        return attached

    def _resolve_soul_path(self, name: str) -> Optional[Path]:
        """Find the SOUL.md for a given agent name."""
        # Direct match in fleet profiles
        direct = _FLEET_PROFILES_DIR / name / "SOUL.md"
        if direct.exists():
            return direct
        # Try case-insensitive
        if _FLEET_PROFILES_DIR.exists():
            for d in _FLEET_PROFILES_DIR.iterdir():
                if d.is_dir() and d.name.lower() == name.lower() and (d / "SOUL.md").exists():
                    return d / "SOUL.md"
        return None

    def _read_soul(self, name: str) -> Optional[SoulDoc]:
        """Read and parse SOUL.md for an agent."""
        path = self._resolve_soul_path(name)
        if not path:
            return None
        return _parse_soul(path.read_text())

    # ── Attach / Detach ────────────────────────────────────────────

    def attach(self, name: str) -> str:
        """Create Hermes profile `agentark-<name>` from SOUL.md.

        Returns a status message.
        """
        soul = self._read_soul(name)
        if not soul:
            available = ", ".join(self.list_available()[:10])
            return f"Unknown agent '{name}'. Available: {available}{'...' if len(self.list_available()) > 10 else ''}"

        profile_name = f"agentark-{name}"
        profile_dir = self.profiles_dir / profile_name

        # Create profile directory with minimal structure
        profile_dir.mkdir(parents=True, exist_ok=True)

        # Copy .env from default profile if available (skip if none exists)
        default_env = HERMES_HOME / ".env"
        dest_env = profile_dir / ".env"
        if default_env.exists() and not dest_env.exists():
            shutil.copy(default_env, dest_env)

        # Write persona
        persona_content = soul_to_persona(soul)
        persona_path = profile_dir / "agent_persona.md"
        persona_path.write_text(persona_content)

        return f"Attached '{name}' → Hermes profile 'agentark-{name}' ({persona_path})"

    def detach(self, name: str) -> str:
        """Remove Hermes profile `agentark-<name>`."""
        profile_name = f"agentark-{name}"
        profile_dir = self.profiles_dir / profile_name

        if not profile_dir.exists():
            return f"Profile 'agentark-{name}' not found — nothing to detach."

        # Deactivate if currently active
        current = self._read_state()
        if current == name:
            self.deactivate()

        shutil.rmtree(profile_dir)
        return f"Detached '{name}' — removed profile '{profile_name}'."

    # ── Activate / Deactivate ──────────────────────────────────────

    def activate(self, name: str) -> str:
        """Set `agentark-<name>` as the active session.

        Writes to ~/.agentark/active_session so shell init can source it.
        Also sets HERMES_PROFILE in the current process for immediate effect.
        """
        # Verify the profile exists
        profile_dir = self.profiles_dir / f"agentark-{name}"
        if not profile_dir.exists():
            return f"Agent '{name}' is not attached yet. Run: agentark session attach {name}"

        STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
        STATE_FILE.write_text(f"agentark-{name}\n")

        # Set for current process
        os.environ["HERMES_PROFILE"] = f"agentark-{name}"

        return (
            f"Activated '{name}' — HERMES_PROFILE=agentark-{name}\n"
            f"\n"
            f"To persist across terminal sessions, add to your shell rc:\n"
            f"  export HERMES_PROFILE=$(cat ~/.agentark/active_session 2>/dev/null)\n"
            f"\n"
            f"Or run 'agentark session deactivate' to return to default."
        )

    def deactivate(self) -> str:
        """Clear the active session — return to default Hermes profile."""
        if STATE_FILE.exists():
            STATE_FILE.unlink()
        os.environ.pop("HERMES_PROFILE", None)
        return "Deactivated — returned to default Hermes profile."

    # ── Show / Status ──────────────────────────────────────────────

    def show(self, name: str) -> Optional[str]:
        """Preview the generated persona content for an agent."""
        soul = self._read_soul(name)
        if not soul:
            return None
        return soul_to_persona(soul)

    def _read_state(self) -> Optional[str]:
        """Read current active session from state file."""
        if STATE_FILE.exists():
            content = STATE_FILE.read_text().strip()
            if content.startswith("agentark-"):
                return content[len("agentark-"):]
            return content
        return None

    def status(self) -> SessionStatus:
        """Return full session state."""
        return SessionStatus(
            active=self._read_state(),
            attached=self.list_attached(),
            available=self.list_available(),
        )
